version: '3'
services:
  app:
    image: diegolirio/redis-as-database:0.1.3-SNAPSHOT
    container_name: app
    restart: always
    ports:
      - 8080:8080
      - 80:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - elasticache
  redis:
    image: redis
    #command: redis-server --requirepass Redis2019!
    networks:
      - elasticache    
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"  
    networks:
      - elasticache    
    #volumes:
    #  - /home/lirio/Workspace/volumes_docker/grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app    
    networks:
      - elasticache    


networks:
  elasticache:
    driver: bridge
