version: '3'
services:
  configserver:
    image: diegolirio/aws-config-server:0.0.1-SNAPSHOT
    container_name: configserver
    restart: always
    ports:
      - 8089:8089
    #networks:
    #  - elasticache      