version: '3'
services:
  app:
    image: diegolirio/redis-as-database:0.1.5-SNAPSHOT
    container_name: app
    restart: always
    ports:
      - 8080:8080
      - 80:8080
    environment:
      - REDIS_HOST=master.redis-cluster-re2.xqc1is.sae1.cache.amazonaws.com
      - REDIS_PORT=6379
    networks:
      - elasticache
  #grafana:
  #  image: grafana/grafana
  #  restart: always
  #  ports:
  #  - "3000:3000"  
  #  networks:
  #    - elasticache
  #prometheus:
  #  image: prom/prometheus:latest
  #  container_name: prometheus
  #  restart: always
  #  ports:
  #  - 9090:9090
  #  command:
  #  - --config.file=/etc/prometheus/prometheus.yml
  #  volumes:
  #  - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #  networks:
  #    - elasticache
  #  depends_on:
  #  - app    


networks:
  elasticache:
    driver: bridge
