global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'appRedis'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'app-redis'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-redis:8080'] #Servidor da minha aplicação