server:
  port: 8089

spring:
   cloud:
     config:
       server:
         git:
           uri: https://github.com/diegolirio/aws-configs-store
     vault:
       port: 8200
       host: ec2-3-221-155-76.compute-1.amazonaws.com
       scheme: http
       authentication: TOKEN
       token: myroot
       kv-version: 2